// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEISmKEp9jyhmt75TfZk6OAl_PkhENpI',
    appId: '1:295760269875:web:0b9982b3dde6d5a65b0946',
    messagingSenderId: '295760269875',
    projectId: 'abw-app-cef3e',
    authDomain: 'abw-app-cef3e.firebaseapp.com',
    storageBucket: 'abw-app-cef3e.firebasestorage.app',
    measurementId: 'G-GV6VKG1VJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJ7BxtMkjqEbUYGYu_eYbfmIDtEWoVNE',
    appId: '1:295760269875:android:b42f3bb0b921562b5b0946',
    messagingSenderId: '295760269875',
    projectId: 'abw-app-cef3e',
    storageBucket: 'abw-app-cef3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFI3vk4vgWVLNz8iFsqtFZf7UWag716E',
    appId: '1:295760269875:ios:cf3c64104186ffe15b0946',
    messagingSenderId: '295760269875',
    projectId: 'abw-app-cef3e',
    storageBucket: 'abw-app-cef3e.firebasestorage.app',
    androidClientId: '295760269875-3bkp992rbjo2360at9bhpqjd17dtnie4.apps.googleusercontent.com',
    iosClientId: '295760269875-1g4n22uk5jtqi4c7n8p38ln4lackdip4.apps.googleusercontent.com',
    iosBundleId: 'com.example.abwApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFI3vk4vgWVLNz8iFsqtFZf7UWag716E',
    appId: '1:295760269875:ios:cf3c64104186ffe15b0946',
    messagingSenderId: '295760269875',
    projectId: 'abw-app-cef3e',
    storageBucket: 'abw-app-cef3e.firebasestorage.app',
    androidClientId: '295760269875-3bkp992rbjo2360at9bhpqjd17dtnie4.apps.googleusercontent.com',
    iosClientId: '295760269875-1g4n22uk5jtqi4c7n8p38ln4lackdip4.apps.googleusercontent.com',
    iosBundleId: 'com.example.abwApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqEISmKEp9jyhmt75TfZk6OAl_PkhENpI',
    appId: '1:295760269875:web:72bc7fd52bd323595b0946',
    messagingSenderId: '295760269875',
    projectId: 'abw-app-cef3e',
    authDomain: 'abw-app-cef3e.firebaseapp.com',
    storageBucket: 'abw-app-cef3e.firebasestorage.app',
    measurementId: 'G-3GGFYXQ7XE',
  );
}
